aurora:
  application:
    name: app
  server:
    port: 8080
  resource:
    static: ""
  consul:
    address: localhost:8500
#gorm配置快
gorm:
  #mysql配置示例
  mysql:
    url:
      - root:duanzhiwen@tcp(82.157.160.117:3306)/test_db?charset=utf8&parseTime=True&loc=Local
#redis配置块
redis:
  #go-redis 配置示例
  go-redis:
    - addr: 82.157.160.117:6379
      password: duanzhiwen
      db: 0
      PoolSize: 100
